#!/usr/bin/env python3
"""Stage 3 of the ROM -> symbols pipeline: emit the N64Recomp TOML inputs.

Merges analysis/out/functions.json with analysis/out/libultra_names.json and
writes:

  config/knife_edge.us.syms.toml   one [[section]] per loaded code segment plus
                                   the boot .bss section (functions = [])
  config/knife_edge.us.toml        the main N64Recomp config

Naming: a function keeps its libultra name when stage 2 assigned one, otherwise
it becomes `func_{vram:08X}` in the boot segment and `func_{vram:08X}_{rom:06X}`
elsewhere.  The ROM suffix is required because six mission overlays are all
based at 0x801D21F0 and eight menu overlays at 0x8017B0C0, so bare VRAM names
would collide - and N64Recomp emits one C function per symbol name, so a
collision is a duplicate C definition.

Section extents use the segment's *ROM* size, not the descriptor's vramEnd: the
.bss tail carries no functions, and a section that stops at the end of the DMA'd
image keeps `rom + (vram - section.vram)` inside the ROM for every function.
No `relocs` key is emitted anywhere - segment_map.md §c establishes that all 69
loads are to fixed addresses with no relocation pass.
"""

import argparse
import json
import os
import sys

import tomlkit

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ident_libultra import load_symbol_lists, DEFAULT_SYMLISTS  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_FUNCS = os.path.join(ROOT, "analysis", "out", "functions.json")
DEFAULT_NAMES = os.path.join(ROOT, "analysis", "out", "libultra_names.json")
DEFAULT_SEGMENTS = os.path.join(ROOT, "analysis", "out", "segments.json")
DEFAULT_CONFIG_DIR = os.path.join(ROOT, "config")
DEFAULT_REPORT = os.path.join(ROOT, "analysis", "out", "syms_report.txt")

ENTRYPOINT = 0x800C2400
SYMS_NAME = "knife_edge.us.syms.toml"
CONFIG_NAME = "knife_edge.us.toml"

# Paths written into the config, relative to config/ (N64Recomp resolves
# relative paths against the config file's own directory).
REL_ROM = "../build/knife_edge.z64"
# Generated recompiled code is committed (functional RE output policy) so CI can
# build without the ROM. Regenerating requires the ROM at build/knife_edge.z64.
REL_OUT = "../generated/us"


# Extra busy-wait yield hooks, for loops find_functions.find_spin_loops() does
# not recognise.  Entries are (segment name, function vram, hook vram, why).
EXTRA_SPIN_YIELD_HOOKS = []


def hexint(v):
    return tomlkit.value("0x%08X" % v)


def hexint6(v):
    return tomlkit.value("0x%06X" % v)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--functions", default=DEFAULT_FUNCS)
    ap.add_argument("--names", default=DEFAULT_NAMES)
    ap.add_argument("--segments", default=DEFAULT_SEGMENTS)
    ap.add_argument("--config-dir", default=DEFAULT_CONFIG_DIR)
    ap.add_argument("--report", default=DEFAULT_REPORT)
    ap.add_argument("--rom-path", default=REL_ROM)
    ap.add_argument("--output-func-path", default=REL_OUT)
    ap.add_argument("--functions-per-file", type=int, default=50)
    ap.add_argument("--symbol-lists", default=DEFAULT_SYMLISTS)
    ap.add_argument("--no-bss", action="store_true",
                    help="omit the boot .bss section entry")
    ap.add_argument("-q", "--quiet", action="store_true")
    args = ap.parse_args(argv)

    funcs = json.load(open(args.functions))
    names_doc = json.load(open(args.names))
    names = names_doc.get("segments", {})
    segments_raw = json.load(open(args.segments))
    bss = next((s for s in segments_raw if s.get("kind") == "bss"), None)

    os.makedirs(args.config_dir, exist_ok=True)

    doc = tomlkit.document()
    doc.add(tomlkit.comment("Generated by analysis/gen_syms.py - do not edit by hand."))
    doc.add(tomlkit.comment("Sources: analysis/out/functions.json, analysis/out/libultra_names.json"))
    sections = tomlkit.aot()

    used_names = {}
    stub_names = {}       # (segment, vram) -> emitted symbol name
    stats = []
    entry_ok = False

    for seg in funcs["segments"]:
        segnames = names.get(seg["name"], {})
        tbl = tomlkit.table()
        tbl["name"] = seg["name"]
        tbl["rom"] = hexint6(seg["rom"])
        tbl["vram"] = hexint(seg["vram"])
        tbl["size"] = hexint6(seg["size"])

        arr = tomlkit.array()
        arr.multiline(True)
        named = 0
        for f in sorted(seg["functions"], key=lambda x: x["vram"]):
            vram = f["vram"]
            size = f["size"]
            assert vram % 4 == 0, "%s: vram %08X not word aligned" % (seg["name"], vram)
            assert size % 4 == 0 and size > 0, \
                "%s: bad size %X at %08X" % (seg["name"], size, vram)
            rom = seg["rom"] + (vram - seg["vram"])
            assert rom % 4 == 0, "%s: rom %X not word aligned" % (seg["name"], rom)
            assert seg["rom"] <= rom and rom + size <= seg["rom"] + seg["size"], \
                "%s: function %08X (rom %X+%X) escapes the section" % (
                    seg["name"], vram, rom, size)

            nm = segnames.get("0x%08X" % vram)
            if nm is None:
                nm = ("func_%08X" % vram if seg["name"] == "boot"
                      else "func_%08X_%06X" % (vram, seg["rom"]))
            else:
                named += 1
            if nm in used_names:
                raise SystemExit("duplicate symbol name %s (%s and %s)" %
                                 (nm, used_names[nm], seg["name"]))
            used_names[nm] = seg["name"]
            stub_names[(seg["name"], vram)] = nm

            if vram == ENTRYPOINT and rom == 0x1000:
                entry_ok = True

            it = tomlkit.inline_table()
            it["name"] = nm
            it["vram"] = hexint(vram)
            it["size"] = hexint6(size)
            arr.append(it)
        tbl["functions"] = arr
        sections.append(tbl)
        stats.append((seg["name"], seg["rom"], len(seg["functions"]), named,
                      len(seg["rejected"])))

    if bss is not None and not args.no_bss:
        boot = next(s for s in funcs["segments"] if s["name"] == "boot")
        tbl = tomlkit.table()
        tbl["name"] = bss["name"]
        # No ROM backing; point at the end of the boot image so the key is
        # present and word aligned.  With functions = [] nothing is ever read.
        tbl["rom"] = hexint6(boot["rom"] + boot["size"])
        tbl["vram"] = hexint(bss["vram"])
        tbl["size"] = hexint6(bss["size"])
        empty = tomlkit.array()
        tbl["functions"] = empty
        sections.append(tbl)
        stats.append((bss["name"], boot["rom"] + boot["size"], 0, 0, 0))

    if not entry_ok:
        raise SystemExit("no function at vram 0x%08X / rom 0x1000 - N64Recomp's "
                         "entrypoint rename would fail" % ENTRYPOINT)

    doc["section"] = sections
    syms_path = os.path.join(args.config_dir, SYMS_NAME)
    with open(syms_path, "w") as fh:
        fh.write(tomlkit.dumps(doc))

    # ---- main config ------------------------------------------------------ #
    cfg = tomlkit.document()
    cfg.add(tomlkit.comment("Generated by analysis/gen_syms.py - do not edit by hand."))
    inp = tomlkit.table()
    inp["entrypoint"] = hexint(ENTRYPOINT)
    inp["symbols_file_path"] = SYMS_NAME
    inp["rom_file_path"] = args.rom_path
    inp["output_func_path"] = args.output_func_path
    inp["functions_per_output_file"] = args.functions_per_file
    # Overlay tracking (analysis/docs/overlay-tracking.md): the hook below calls
    # librecomp's overlay bookkeeping from the game's single DMA primitive, so the
    # generated code needs the extern declarations.
    inp["recomp_include"] = (
        '#include "recomp.h"\n'
        "#ifdef __cplusplus\n"
        'extern "C" {\n'
        "#endif\n"
        "/* src/main/register_overlays.cpp - whole-section overlay tracking. */\n"
        "extern void ke_overlay_dma(uint32_t rom, int32_t ram_addr, uint32_t size);\n"
        "/* ultramodern/src/scheduling.cpp - pumps the external message queue and\n"
        "   yields to any higher-priority ready thread; used by SPIN_YIELD_HOOKS. */\n"
        "extern void yield_self_1ms(uint8_t* rdram);\n"
        "#ifdef __cplusplus\n"
        "}\n"
        "#endif"
    )
    cfg["input"] = inp
    # Names that N64Recomp does not already know about are emitted verbatim as C
    # functions, so anything matching a libc/libm identifier (fabs, fabsf,
    # _bzero, _Printf, ...) collides with the real declaration in <math.h> etc.
    # Route every such name through [patches].renamed so it is emitted as
    # `<name>_recomp`; the body is still recompiled normally.
    sets = load_symbol_lists(args.symbol_lists)
    known = set().union(*sets.values())
    to_rename = sorted(n for n in used_names
                       if n not in known and not n.startswith("func_"))

    # OS-level functions that must not execute but that stage 2 could not name
    # (ident_libultra.STUB_FUNCS).  N64Recomp emits an empty body for each, so
    # the symbol still exists for jal resolution but the original MMIO-touching
    # code never runs.
    patches = tomlkit.table()
    stub_arr = tomlkit.array()
    stub_arr.multiline(True)
    for s in names_doc.get("stubs", []):
        vram = int(s["vram"], 16)
        nm = stub_names.get((s["segment"], vram))
        if nm is None:
            raise SystemExit("stub target %s %s has no emitted symbol"
                             % (s["segment"], s["vram"]))
        stub_arr.append(nm)
    patches["stubs"] = stub_arr
    patches["ignored"] = tomlkit.array()
    ren = tomlkit.array()
    ren.multiline(True)
    for n in to_rename:
        ren.append(n)
    patches["renamed"] = ren
    cfg["patches"] = patches

    # Overlay-tracking hook: func_800D1D10(devAddr, dramAddr, size) is the single
    # funnel for every ROM->RAM DMA (segment_map.md). Registering the range with
    # librecomp before the copy is fine - the lookup tables never read rdram.
    # devAddr is masked in case it is KSEG1/phys-based rather than a raw ROM offset.
    # ke_overlay_dma() wraps librecomp's unload_overlays/load_overlays pair so the
    # unload range is grown to whole-section granularity; see
    # src/main/register_overlays.cpp and analysis/docs/boot-debug.md.
    hook = tomlkit.table()
    hook["func"] = "func_800D1D10"
    hook["text"] = (
        "ke_overlay_dma(((uint32_t)ctx->r4) & 0x1FFFFFFF, "
        "(int32_t)ctx->r5, (uint32_t)ctx->r6);"
    )
    hooks = tomlkit.aot()
    hooks.append(hook)

    # Busy-wait yield hooks (analysis/docs/boot-debug.md).
    #
    # ultramodern schedules game threads cooperatively: messages posted from
    # native threads (VI retrace, SP/DP done, PI) sit in an external queue and
    # are only drained when a *game* thread calls osSendMesg/osRecvMesg/osJamMesg
    # or blocks.  A recompiled thread that spins on a memory flag therefore
    # deadlocks the whole runtime - on hardware the same loop is preempted by
    # the RCP interrupt handler, which has no equivalent here.
    #
    # N64Recomp only rewrites the unconditional `b .` form into pause_self(), so
    # the conditional form needs an explicit hook.  yield_self_1ms() drains the
    # external queue (waiting at most 1 ms) and hands execution to a higher
    # priority ready thread, which is what the interrupt would have done.
    #
    # The loops come from find_functions.find_spin_loops(); the hook goes at the
    # top of the loop body so it runs once per iteration.  Functions whose name
    # puts them in reimplemented_funcs/ignored_funcs are skipped: N64Recomp
    # emits no body for them, so there is nothing to hook (and librecomp's own
    # implementation blocks properly).
    spins = []
    for seg in funcs["segments"]:
        for sl in seg.get("spin_loops", []):
            spins.append((seg["name"], sl["func"], sl["target"], sl["branch"]))
    for segname, func_vram, hook_vram, branch_vram in spins:
        nm = stub_names.get((segname, func_vram))
        if nm is None or nm in sets["reimplemented_funcs"] or nm in sets["ignored_funcs"]:
            continue
        h = tomlkit.table()
        h.add(tomlkit.comment(
            "polling loop %08X..%08X (find_functions.find_spin_loops)"
            % (hook_vram, branch_vram)))
        h["func"] = nm
        h["before_vram"] = hexint(hook_vram)
        h["text"] = "yield_self_1ms(rdram);"
        hooks.append(h)
    for segname, func_vram, hook_vram, why in EXTRA_SPIN_YIELD_HOOKS:
        nm = stub_names.get((segname, func_vram))
        if nm is None:
            raise SystemExit("spin-yield hook target %s %08X is not an emitted "
                             "function" % (segname, func_vram))
        h = tomlkit.table()
        h.add(tomlkit.comment(why))
        h["func"] = nm
        h["before_vram"] = hexint(hook_vram)
        h["text"] = "yield_self_1ms(rdram);"
        hooks.append(h)
    patches["hook"] = hooks
    cfg_path = os.path.join(args.config_dir, CONFIG_NAME)
    with open(cfg_path, "w") as fh:
        fh.write(tomlkit.dumps(cfg))

    L = ["section              rom      functions  named  rejected"]
    for name, rom, n, named, rej in stats:
        L.append("%-20s %06X %9d %6d %9d" % (name, rom, n, named, rej))
    L.append("")
    L.append("total sections : %d" % len(stats))
    L.append("total functions: %d" % sum(s[2] for s in stats))
    L.append("named functions: %d" % sum(s[3] for s in stats))
    L.append("wrote %s" % syms_path)
    L.append("wrote %s" % cfg_path)
    report = "\n".join(L) + "\n"
    with open(args.report, "w") as fh:
        fh.write(report)
    if not args.quiet:
        sys.stdout.write(report)
    return 0


if __name__ == "__main__":
    sys.exit(main())
